# docker-compose.yml
version: '3.9'

services:
  voice-chat-backend:
    image: kaitaoms/voice-chat-backend:latest   # 换成你实际推到的仓库/tag
    init: true                                
    
    ports:
      - "8000:8000"

    environment:
      PYTHONUNBUFFERED: "1"
      MODELSCOPE_CACHE: /app/model_cache

    volumes:
      - model_cache_data:/app/model_cache     # 命名卷，缓存模型

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  model_cache_data:
